# fly.toml app configuration file generated for myvideo on 2023-07-06T13:49:38+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "myvideo"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
